### PR TITLE
add Ruby 2.5.1 integration

### PR DESCRIPTION
**Pull request by takkanm**

### CODE REVIEW

**Comment by yahonda** [comment]
CI failures can be addressed by https://github.com/yahonda/stateful_enum/commit/e16d846567c5b7b2c111ce71411ee004a9525de6

Then it will get errors like https://travis-ci.org/yahonda/stateful_enum/jobs/376650728 It looks like due to https://github.com/rails/rails/issues/25125 . I do not think Ruby 2.5.1 support Rails 4.1.

**Comment by yahonda** [comment]
Excluded a "unsupported" combination by https://github.com/yahonda/stateful_enum/commit/484638ae81737c382af14a2bbf52f856b744737b

**Comment by takkanm** [comment]
@yahonda Thank you for your support. I'll pick up your commits to this branch.

**Comment by amatsuda** [comment]
Thank you!

**Pull request merged**
